name: memex
channels:
    - blaze
    - memex
    - quasiben
dependencies:
    - bokeh=0.7.0
    - blaze=0.7.0
    - python=2.7.8
    - nutch
    - ache=0.2.0
    - django=1.7.3
    - solr=4.10.2
    - gunicorn
    - pytest
    - pip
    - sphinx
    - jinja2
    - redis
    - redis-py
    - pip:
        - tld
        - selenium
        - coverage
        - pytest-cov
        - pytest-django
        - pytest-ordering
        - django-crispy-forms
        - coveralls
        - sphinx-rtd-theme
        - celery
        - elasticsearch
        - docker-compose
